### ISSUE TITLE
Does this runs on Linux?

### ISSUE THREAD

**Issue by BenHerbst** [MambaCodes/BeAnonymous#3]
Am I able to run this on my Arch Linux?
If not, please add support for it and add to the AUR. Thanks

**Comment by iamDyeus** [comment]
Hello there @BenHerbst 
this was a Minor project which I developed in the span of one week, therefore I had no intention of making it Compatible with  Linux or  MacOS. But if in future the Number of  Contributors on this project Increases then I'll surely consider making it Compatible for Arch Linux.
